version: '2'

services:
  postgres:
    image: postgres:14.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_USER: postgres
      PGDATA : /var/lib/postgresql/data/pgdata

volumes:
  pg_data:
